### ISSUE TITLE
Composer + Outdated

### ISSUE THREAD

**Issue by mathieutu** [r-a-stone/Laravel-Auth-Bridge#10]
Hi, 
I have several problems :
- The install via composer failed : 

```
Installing webcode/phpbb-bridge (1.0.x-dev a21b93e)
   Downloading: connection... 
   Failed to download webcode/phpbb-bridge from dist: The "https://api.github.com/repos/r-a-stone/BridgeBB/zipball/a21b93e3f2edb8f7ce36429c59826c094644d927" file could not be downloaded (HTTP/1.1 404 Not Found)
```
- And then, the auth method for PhpBB is apparently totally outdated.
  https://wiki.phpbb.com/Authentication_providers

Do you think you could do something to update your awesome bridge ?
(I think this is the only one between laravel and phpbb..?)
Thank you !

**Comment by r-a-stone** [comment]
I will try to find time this weekend to take a look at this

**Comment by mathieutu** [comment]
Amazing!
I've contacted a fork dev, which has apparently made a new phpBB 3.1 extension for auth,
I'm waiting for his answer, and let you know when I have it.

**Comment by ghost** [comment]
I am also very interested in this Bridge. Please let us know if your progress. I am happy to help you cost if you can explain what needs to be done. 

I am insanely keen to get this working Laravel 5. It would solve a problem I've had for years. 

Thanks for all your hard work and sharing this with us.

**Comment by mathieutu** [comment]
Hi guy !
It's ok, the fork i was waiting was updated.
After few modifications It's fully operational (and documented) with laravel 4.2 and phpBB 3.1.3 : 

I'm working on the groups managment, if anybody can help it will be awesome !

https://github.com/mathieutu/Laravel-Auth-Bridge
