### ISSUE TITLE
Installation - Can't use method return value in write context in 

### ISSUE THREAD

**Issue by totha** [r-a-stone/Laravel-Auth-Bridge#3]
During installation on:

php artisan config:publish webcode/bridgebb

error:

PHP Fatal error:  Can't use method return value in write context in (...) /vendor/webcode/phpbb-bridge/src/Webcode/BridgeBB/BridgeBBServiceProvider.php on line 20
{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Can't use method return value in write context","file":"(...) \/vendor\/webcode\/phpbb-bridge\/src\/Webcode\/BridgeBB\/BridgeBBServiceProvider.php","line":20}}

Environment: debian wheezy, php 5.4.4, 
would it work on php 5.5?

**Comment by totha** [comment]
bump

**Comment by r-a-stone** [comment]
I will have a stable branch soon, the head is no longer stable.

**Comment by totha** [comment]
I see, cool :)
