### ISSUE TITLE
Class not Found

### ISSUE THREAD

**Issue by kremsy** [r-a-stone/Laravel-Auth-Bridge#5]
I somehow can't get it working anymore since I made a composer update, I tried already to isntall, remove, but I have the problem that it does not find the class.

I added to the service providers:
        'Webcode\BridgeBB\BridgeBBServiceProvider',

On Laravel appears than "Class 'Webcode\BridgeBB\BridgeBBServiceProvider' not found".
But the files are existing in the vendor folder.

If I make an clear-compiled command I get the following output:
php artisan clear-compiled
PHP Fatal error:  Class 'Webcode\BridgeBB\BridgeBBServiceProvider' not found in /var/www/virtual/league.paragon-esports.com/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 158
{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Class 'Webcode\BridgeBB\BridgeBBServiceProvider' not found","file":"\/var\/www\/virtual\/league.paragon-esports.com\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/ProviderRepository.php","line":158}}

Hope you can help me out there :+1: 

I also see that in the newest version the User and Group models are not existing anymore, are the users now managed manually, is there still a possability to force an user for example in an admin group?

**Comment by kremsy** [comment]
The class not found issue lends due differences between namespaces, foldernames and classnames sometimes the BB is big written sometimes small.

If I change the Provider to 'Webcode\Bridgebb\BridgebbServiceProvider', rename the folder to Bridgebb and the php file to BridgebbServiceProvider it works, think you should fix that up ;).

Thanks for your great tool, would be nice to see it finished with the login features.

**Comment by r-a-stone** [comment]
I just did some updates to the 1.0 branch, did this resolve this issue? (thank you for your pull request by the way!)

**Comment by kremsy** [comment]
How to use the branch 1.0?         "webcode/phpbb-bridge": "1.0"  does not work, but I will try to update on the dev-master

**Comment by kremsy** [comment]
I tried to update it with dev-master and the issue is fixed (y)
